openapi: 3.0.0
info:
  title: Exchange Rate Package
  version: 1.0.0
servers:
  - url: /api/exchange-rate
paths:
  /:
    post:
      operationId: get-exchange-rate
      summary: Get price in different currencies
      tags:
        - Exchange Rate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                currency:
                  type: string
      responses:
        "200":
          "description": "OK"
        "401":
          "description": "Unauthorized"
        "404":
          "description": "Page not found"
        "422":
          "description": "Unprocessable Entity"
        "500":
          "description": "Internal server error"

